---
- name: Update all packages
  yum: name=* state=latest

- name: Define ocp_dependencies.
  set_fact:
    ocp_dependencies: "{{ __ocp_dependencies | list }}"
  when: ocp_dependencies is not defined

- name: Ensure OpenShift dependencies are installed.
  become: yes
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ ocp_dependencies }}"

- name: Add insecure registry and logs to docker OPTIONS
  become: yes
  replace:
   dest: /etc/sysconfig/docker
   regexp: '^OPTIONS=.*'
   replace: 'OPTIONS="--selinux-enabled --insecure-registry {{ openshift_prepare_services_subnet }} --log-opt max-size={{ openshift_prepare_log_max_size }} --log-opt max-file={{ openshift_prepare_log_max_file }}"'
   backup: yes

- name: Enable docker service
  become: yes
  service:
    name: docker
    state: started
    enabled: yes


