---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Installing all dependencies
  become: yes
  include_tasks: install.yml

- name: Generate and send SSH Key from master to all
  include_tasks: ssh_key.yml
  