---
  - name: Checking inventory
    import_playbook: prerequisites.yml

  - name: Installing all Pre-Requisites
    hosts: all
    roles: 
      - prerequisites_ocp

  - name: Install OCP
    hosts: ocp_master
    roles: 
      - install_ocp