---
  - name: Checking inventory
    import_playbook: prerequisites.yml

  - name: Installing all Pre-Requisites
    become: yes
    hosts: all
    roles: 
      - prerequisites_ocp

  - name: Create SSH Keys and send to other nodes
    hosts: all
    roles: 
      - key_distribution